export enum ColorActionName {
    LIGHTEN = "lighten",
    BRIGHTEN = "brighten",
    DARKEN = "darken",
    DESATURATE = "desaturate",
    SATURATE = "saturate",
    GREYSCALE = "greyscale",
    SPIN = "spin",
    HUE = "hue",
    MIX = "mix",
    TINT = "tint",
    SHADE = "shade",
    XOR = "xor",
    RED = "red",
    GREEN = "green",
    BLUE = "blue",
}